version: '3'

services:
    php-fpm:
        build:
            context: etc/devel/docker/php-fpm
        image: nasa/php-fpm
        container_name: nasa.php-fpm
        volumes:
            - ".:/app"
        extra_hosts:
            - "docker.host:${DOCKER_HOST_IP}"
            - "rovers-control-panel.nasa.org:172.19.0.3"
        networks:
            nasa_net:
                ipv4_address: 172.19.0.2
        tty: true

    nginx:
        build:
            context: etc/devel/docker/nginx
        image: nasa/nginx
        depends_on:
            - php-fpm
        container_name: nasa.nginx
        ports:
            - 443:443
        networks:
            nasa_net:
                ipv4_address: 172.19.0.3
        tty: true

networks:
    nasa_net:
        driver: bridge
        ipam:
            config:
            - subnet: 172.19.0.0/24
