services:
    rover_panel_control.rover_panel_control_controller:
      class: RoverControlPanel\UserInterface\Api\RoverControlPanelController
      arguments:
        - '@request_stack'
        - '@rover_panel_control.rover_squad_exploration_use_case'
      public: true

    rover_panel_control.rover_squad_exploration_use_case:
      class: RoverControlPanel\Application\UseCase\Rover\RoverSquadExplorationUseCase
      arguments:
        - '@rover_control_panel.rover_squad_data_transformer'
      public: true

    rover_control_panel.rover_squad_data_transformer:
      class: RoverControlPanel\Application\DataTransformer\Rover\RoverSquadDataTransformer
      public: true